"""Content of the bonus "Archaeology and the Bible: 12 Discoveries That Illuminate
the Biblical Story". Dates are approximate. KJV verses are copied from the KJV text.

Each entry separates:
  evidence  - what the object itself directly shows
  context   - the historical background it provides
  bible     - how it relates to the biblical account
"""

DISCOVERIES = [
    {
        "name": "The Merneptah Stele",
        "date": "c. 1208 BC",
        "art": "stele",
        "found": "1896, by Flinders Petrie, in the funerary temple of Pharaoh Merneptah at Thebes, Egypt",
        "kept": "Egyptian Museum, Cairo",
        "object": "A granite slab about 3 metres high, inscribed in Egyptian hieroglyphs",
        "what": "A large royal inscription celebrating Pharaoh Merneptah's victories in his fifth year as king. Most of the text concerns his war against the Libyans; the closing lines list peoples and places in Canaan that he claims to have defeated.",
        "evidence": "One line names <em>Israel</em>, saying that Israel was laid waste and its seed was no more (a boast of victory). In the hieroglyphs, the name Israel is marked with the sign for a people, while the other names in the list are marked as places or lands. It is generally regarded as the earliest known mention of Israel outside the Bible.",
        "context": "The stele shows that by about 1208 BC a group called Israel was known in Canaan, important enough to be listed among Pharaoh's enemies. It does not describe how or when Israel came to be there, and the victory it claims is royal propaganda typical of Egyptian inscriptions.",
        "bible": "The Bible describes Israel living in Canaan among other peoples during the time of the Judges. The stele agrees that Israel was present in the land as a people at that general period. Scholars hold different views on the date of the Exodus and the conquest; the stele fits several of these views because it only shows that Israel was already there by about 1208 BC.",
        "refs": "Joshua 24:31; Judges 1–3",
        "verse": ("Judges 3:5", "And the children of Israel dwelt among the Canaanites, Hittites, and Amorites, and Perizzites, and Hivites, and Jebusites:"),
        "handbook": "On the Handbook's biblical timeline, find the conquest of the Promised Land and the beginning of the period of the Judges. The Handbook follows an early date for the Exodus (c. 1445 BC), which places Merneptah's reign within the period of the Judges. Read the stele alongside the Handbook's presentation of the books of Joshua and Judges.",
        "question": "Israel appears in history as a people in the land God had promised. How does it encourage you that God's promises to Abraham took shape in real places and among real nations?",
    },
    {
        "name": "The Mesha Stele (the Moabite Stone)",
        "date": "c. 840 BC",
        "art": "stele2",
        "found": "1868, at Dhiban (biblical Dibon) in present-day Jordan. It was broken into pieces in 1869, but an impression of the text had already been taken, which allowed it to be reconstructed",
        "kept": "Musée du Louvre, Paris",
        "object": "A black basalt slab about 1.1 metres high, with 34 lines in the Moabite language",
        "what": "An inscription set up by Mesha, king of Moab, describing how he freed Moab from Israelite control and rebuilt towns in his land.",
        "evidence": "Mesha names <em>Omri, king of Israel</em>, and says that Omri and his son oppressed Moab for many years because Chemosh, the god of Moab, was angry with his land. He describes taking Israelite towns and mentions taking vessels of <em>YHWH</em>, the God of Israel, from Nebo. One damaged line has been read by some scholars as a mention of the “house of David”, but this reading is debated.",
        "context": "The stele shows that Moab was under Israel's control during the dynasty of Omri, and that Moab later broke free. It also shows how a neighbouring king described his victories in religious terms, crediting his god Chemosh. It is one of the oldest inscriptions that mention the God of Israel by name.",
        "bible": "2 Kings 3 records that Mesha king of Moab paid tribute to the king of Israel and rebelled after Ahab's death. The Bible and the stele describe the same relationship from opposite sides. Each account tells the events from its own point of view: the stele does not mention the campaign of Israel, Judah and Edom against Moab described in 2 Kings 3, and the Bible does not list Mesha's building projects.",
        "refs": "1 Kings 16:21–28; 2 Kings 1:1; 3:4–27",
        "verse": ("2 Kings 3:5", "But it came to pass, when Ahab was dead, that the king of Moab rebelled against the king of Israel."),
        "handbook": "In the Handbook's visual table of the kings of Israel and Judah, find Omri, Ahab and Jehoram (Joram). On the biblical timeline, these kings belong to the Kingdom of the North (Israel) after the division of the kingdom, in the time of the prophets Elijah and Elisha.",
        "question": "Mesha gave the glory for his victories to Chemosh. When you look back on the good things in your own life, to whom do you give the credit, and why?",
    },
    {
        "name": "The Tel Dan Stele",
        "date": "9th century BC (second half)",
        "short_date": "9th century BC",
        "art": "fragments",
        "found": "1993 and 1994, by the excavation team of Avraham Biran at Tel Dan in northern Israel; the pieces had been reused in a later wall",
        "kept": "Israel Museum, Jerusalem",
        "object": "Three fragments of a basalt victory inscription in Aramaic",
        "what": "Part of a monument set up by a king of Aram-Damascus to celebrate his victories over his enemies. The king's name is not preserved; many scholars attribute the inscription to Hazael.",
        "evidence": "The text mentions a “king of Israel” and contains the phrase <em>bytdwd</em>, “house of David”. Most scholars understand this as a name for the kingdom of Judah, ruled by David's descendants. The damaged lines also refer to the killing of a king of Israel and a king of the house of David; their names are partly restored by scholars, often as Joram and Ahaziah.",
        "context": "This is the earliest widely accepted reference to David outside the Bible. Written about 150 years after David's time, it shows that the ruling family of Judah was known by his name to a foreign king.",
        "bible": "The Bible presents David as the founder of a royal line in Judah, and records wars between Israel and Aram in the time of Hazael. 2 Kings 9 records that Jehu killed Joram of Israel and Ahaziah of Judah. If the restored names are correct, the stele's author claims these deaths for himself. Historians discuss how the two accounts relate; one suggestion is that the Aramean king presented events in which Jehu acted as his own victory.",
        "refs": "2 Samuel 7:11–16; 2 Kings 8:7–15, 28–29; 9:14–29",
        "verse": ("2 Kings 8:28", "And he went with Joram the son of Ahab to the war against Hazael king of Syria in Ramoth-gilead; and the Syrians wounded Joram."),
        "handbook": "Use the Handbook's visual table of the kings of Israel and Judah to locate Joram of Israel and Ahaziah of Judah, and the timeline to see the divided kingdom: Israel in the North and Judah in the South, where David's descendants reigned.",
        "question": "A foreign king called Judah “the house of David”. What does God's promise of a lasting house for David (2 Samuel 7) mean for you as you read the rest of the Bible?",
    },
    {
        "name": "The Black Obelisk of Shalmaneser III",
        "date": "c. 825 BC (records events of 841 BC)",
        "short_date": "c. 825 BC",
        "art": "obelisk",
        "found": "1846, by Austen Henry Layard, at Nimrud (ancient Kalhu) in present-day Iraq",
        "kept": "British Museum, London",
        "object": "A black limestone pillar about 2 metres high, with five rows of carved panels and an Assyrian inscription",
        "what": "A monument of the Assyrian king Shalmaneser III recording his military campaigns and the tribute he received from several rulers.",
        "evidence": "One panel shows a man bowing to the ground before the Assyrian king, followed by servants carrying gifts. The caption calls it the tribute of <em>Jehu, son of Omri</em>. “Son of Omri” was the Assyrian way of referring to the king of Israel, the land of the house of Omri; Jehu was not Omri's descendant. Scholars discuss whether the kneeling figure is Jehu himself or his envoy.",
        "context": "The obelisk shows that the kingdom of Israel paid tribute to Assyria in Jehu's time (841 BC), as Assyria's power was growing in the region. It is one of the earliest surviving pictures of an Israelite king or his representative.",
        "bible": "The Bible describes Jehu as king of Israel after Joram and records that, in his days, Hazael of Aram attacked Israel. It does not mention Jehu's tribute to Assyria. The obelisk adds a detail from the Assyrian side; some historians suggest that Jehu sought Assyria's favour while Israel was under pressure from Aram.",
        "refs": "2 Kings 9–10",
        "verse": ("2 Kings 10:32", "In those days the LORD began to cut Israel short: and Hazael smote them in all the coasts of Israel;"),
        "handbook": "Find Jehu in the Handbook's visual table of the kings of Israel and Judah, and read the Handbook's presentation of the books of Kings to see where his reign fits in the history of the Northern Kingdom.",
        "question": "Jehu bowed before a powerful earthly king. In what situations are you tempted to look for security in human power rather than in God?",
    },
    {
        "name": "The Siloam Inscription and Hezekiah's Tunnel",
        "date": "c. 700 BC",
        "art": "tunnel",
        "found": "The tunnel was known before modern times; the inscription was found inside it in 1880, near its southern end",
        "kept": "Inscription: Istanbul Archaeology Museums. The tunnel can still be walked through in Jerusalem",
        "object": "A Hebrew inscription of six lines, cut into the wall of a water tunnel about 533 metres long",
        "what": "A tunnel cut through solid rock to bring water from the Gihon Spring, outside the old city wall of Jerusalem, to a pool inside the city.",
        "evidence": "The inscription describes the moment when two teams of workers, digging from opposite ends, heard each other's voices and broke through to meet. It says that the water then flowed from the spring to the pool for 1,200 cubits. It does not name the king who ordered the work.",
        "context": "The tunnel shows the engineering skill of Jerusalem's builders and the importance of securing the city's water supply in a time of war. Most scholars date the inscription and the tunnel to the reign of Hezekiah, around 700 BC, mainly from the style of the Hebrew script and the biblical description; a few have proposed other dates.",
        "bible": "The Bible records that Hezekiah made a pool and a conduit and brought water into the city, and that he stopped the upper watercourse of Gihon and brought it down to the west side of the city of David. The tunnel matches this description well, and is widely identified with Hezekiah's work.",
        "refs": "2 Kings 20:20; 2 Chronicles 32:2–4, 30; Isaiah 22:9–11",
        "verse": ("2 Kings 20:20", "And the rest of the acts of Hezekiah, and all his might, and how he made a pool, and a conduit, and brought water into the city, are they not written in the book of the chronicles of the kings of Judah?"),
        "handbook": "Find Hezekiah in the Handbook's visual table of the kings of Israel and Judah. On the biblical timeline, his reign follows the fall of Samaria (722 BC), in the time of the prophets Isaiah and Micah.",
        "question": "Hezekiah prepared wisely for danger and also prayed to the LORD (2 Kings 19). How do you hold together careful planning and trust in God?",
    },
    {
        "name": "Sennacherib's Prism",
        "date": "c. 691–689 BC (records the campaign of 701 BC)",
        "short_date": "c. 691–689 BC",
        "art": "prism",
        "found": "Several copies of Sennacherib's annals are known. The Taylor Prism, from Nineveh, was obtained by Colonel Robert Taylor in 1830",
        "kept": "Taylor Prism: British Museum, London. Other copies: Oriental Institute, Chicago, and Israel Museum, Jerusalem",
        "object": "Six-sided clay prisms inscribed in Akkadian cuneiform",
        "what": "The official annals of the Assyrian king Sennacherib, describing his military campaigns, including his third campaign in 701 BC against the Levant and Judah.",
        "evidence": "Sennacherib names <em>Hezekiah of Judah</em>. He claims to have besieged and captured 46 of Hezekiah's fortified cities and to have shut Hezekiah up in Jerusalem “like a bird in a cage”. He lists the tribute Hezekiah sent, including 30 talents of gold and 800 talents of silver. He does not claim to have captured Jerusalem.",
        "context": "The prism shows, from the Assyrian side, that a major Assyrian invasion of Judah took place in 701 BC. Its account is written to glorify the Assyrian king; it says nothing of why the campaign ended without the capture of Jerusalem.",
        "bible": "The Bible also describes Sennacherib's invasion, the capture of Judah's fortified cities and Hezekiah's tribute: thirty talents of gold (the same figure as the prism) and three hundred talents of silver (the prism gives a higher figure). It then records that Jerusalem was delivered and that Sennacherib returned to Nineveh. The two accounts agree on the main events and differ in emphasis and in some details.",
        "refs": "2 Kings 18:13–19:37; 2 Chronicles 32:1–23; Isaiah 36–37",
        "verse": ("2 Kings 18:13", "Now in the fourteenth year of king Hezekiah did Sennacherib king of Assyria come up against all the fenced cities of Judah, and took them."),
        "handbook": "Read this together with the Handbook's presentation of 2 Kings and Isaiah, and find Hezekiah in the visual table of the kings of Israel and Judah.",
        "question": "Hezekiah took Sennacherib's threatening letter and spread it before the LORD (2 Kings 19:14). What “letter” or worry would you like to bring before God today?",
    },
    {
        "name": "The Ketef Hinnom Silver Scrolls",
        "date": "late 7th or early 6th century BC",
        "short_date": "c. 600 BC",
        "art": "amulet",
        "found": "1979, by Gabriel Barkay's team, in a burial cave at Ketef Hinnom, on the slope of the Hinnom Valley in Jerusalem",
        "kept": "Israel Museum, Jerusalem",
        "object": "Two tiny rolled sheets of silver, worn as amulets, inscribed in ancient Hebrew script",
        "what": "Two small silver scrolls, only a few centimetres long. They were so fragile that it took several years to unroll them safely and read the faint text.",
        "evidence": "Both scrolls contain a blessing very close to the priestly blessing of Numbers 6:24–26, including the divine name <em>YHWH</em>. Most scholars date them to the late 7th or early 6th century BC, the last years of the kingdom of Judah; a few have argued for a later date.",
        "context": "These are the oldest known objects bearing words that are also found in the Bible, older than the Dead Sea Scrolls by several centuries. They show that this blessing was known and treasured by people in Jerusalem before the Babylonian exile.",
        "bible": "The scrolls contain a form of the blessing that the LORD gave to Aaron and his sons to speak over Israel. They do not by themselves tell us when the book of Numbers was written, but they show that the words of this blessing were in use in Judah at this time.",
        "refs": "Numbers 6:22–27",
        "verse": ("Numbers 6:24–26", "The LORD bless thee, and keep thee: The LORD make his face shine upon thee, and be gracious unto thee: The LORD lift up his countenance upon thee, and give thee peace."),
        "handbook": "Read the Handbook's presentation of the book of Numbers. Then, on the biblical timeline, look at the final years of the kingdom of Judah and the ministry of Jeremiah, the period from which these scrolls most probably come.",
        "question": "Someone in ancient Jerusalem carried these words of blessing with them. Which words of Scripture do you carry with you, and how do they shape your days?",
    },
    {
        "name": "The Babylonian Chronicle of Nebuchadnezzar",
        "date": "records events of 605–594 BC, including March 597 BC",
        "short_date": "597 BC",
        "art": "tablet",
        "found": "Part of a series of Babylonian chronicle tablets held in the British Museum; this tablet was first published in 1956",
        "kept": "British Museum, London",
        "object": "A small clay tablet inscribed in Akkadian cuneiform",
        "what": "A brief year-by-year record of the first years of Nebuchadnezzar II, king of Babylon, including the battle of Carchemish (605 BC) and his campaigns in the west.",
        "evidence": "For Nebuchadnezzar's seventh year, the chronicle records that he besieged “the city of Judah”, captured it on the second day of the month Adar (March 597 BC), seized its king, appointed a king of his own choice, and took heavy tribute to Babylon.",
        "context": "This entry gives one of the most precise dates in the history of ancient Judah. It shows Judah caught between the great powers of Egypt and Babylon in the years before the destruction of Jerusalem.",
        "bible": "2 Kings 24 records that Nebuchadnezzar besieged Jerusalem, took King Jehoiachin to Babylon with treasures and many people, and made Mattaniah, renamed Zedekiah, king in his place. The chronicle does not give the kings' names but describes the same events. It dates them to Nebuchadnezzar's seventh year, while 2 Kings 24:12 says the eighth year; scholars generally explain this by different ways of counting a king's years.",
        "refs": "2 Kings 24:8–17; 2 Chronicles 36:9–10; Jeremiah 46:2",
        "verse": ("2 Kings 24:12", "And Jehoiachin the king of Judah went out to the king of Babylon, he, and his mother, and his servants, and his princes, and his officers: and the king of Babylon took him in the eighth year of his reign."),
        "handbook": "On the Handbook's biblical timeline, find the final years of the kingdom of Judah, King Zedekiah (598–587 BC) and the deportation of the inhabitants of Judah to Babylon. Ezekiel and Daniel, also on the timeline, were among those taken into exile in this period.",
        "question": "The prophets had warned Judah for many years before these events. How do you respond when God's Word calls you to change direction?",
    },
    {
        "name": "The Lachish Letters",
        "date": "c. 588–586 BC",
        "art": "ostracon",
        "found": "1935 (with a few more in 1938), by the expedition of James Leslie Starkey at Tell ed-Duweir, ancient Lachish, in a room near the city gate",
        "kept": "British Museum, London, and Israel Museum, Jerusalem",
        "object": "Pieces of broken pottery (ostraca) with letters written in ink in ancient Hebrew",
        "what": "Military letters, mostly sent by an officer named Hoshayahu to Yaush, apparently the commander at Lachish, during the Babylonian invasion of Judah.",
        "evidence": "In Letter 4, the writer says that he and his men are watching for the fire signals of Lachish, because they cannot see Azekah. Other letters mention a prophet, whose name is not preserved, and reflect the anxious situation of the officers.",
        "context": "These letters give a rare first-hand view of Judah's last days before the fall of Jerusalem, written by people living through the Babylonian attack. Many historians understand the remark about Azekah to mean that Azekah had already fallen or could no longer send signals.",
        "bible": "Jeremiah 34:7 says that when the Babylonian army fought against Jerusalem, Lachish and Azekah were the last fortified cities of Judah still standing. The letters fit this situation closely.",
        "refs": "Jeremiah 34:1–7; 2 Kings 25:1–2",
        "verse": ("Jeremiah 34:7", "When the king of Babylon’s army fought against Jerusalem, and against all the cities of Judah that were left, against Lachish, and against Azekah: for these defenced cities remained of the cities of Judah."),
        "handbook": "On the Handbook's biblical timeline, find the ministry of Jeremiah (626–586 BC), King Zedekiah, and the fall of Jerusalem (587 or 586 BC).",
        "question": "The officers at Lachish watched anxiously for signals in a time of crisis. Where do you look for guidance and hope when everything around you is uncertain?",
    },
    {
        "name": "The Cyrus Cylinder",
        "date": "c. 539–538 BC",
        "art": "cylinder",
        "found": "1879, by Hormuzd Rassam, in the ruins of Babylon, in present-day Iraq",
        "kept": "British Museum, London",
        "object": "A barrel-shaped clay cylinder, about 23 centimetres long, inscribed in Akkadian cuneiform",
        "what": "A royal inscription written after Cyrus the Great of Persia took Babylon in 539 BC, presenting him as a just ruler chosen by Marduk, the god of Babylon.",
        "evidence": "Cyrus states that he returned the images of gods to their sanctuaries in several cities and gathered their former inhabitants and returned them to their homes. The cities named are in Mesopotamia and western Iran. The cylinder does not mention Judah, Jerusalem or the Jews.",
        "context": "The cylinder shows the general policy of Cyrus: allowing displaced peoples to return home and restore their places of worship, partly to win their loyalty. It is written in the language of Babylonian royal propaganda.",
        "bible": "The Bible records that Cyrus issued a decree allowing the Jews to return to Jerusalem and rebuild the house of the LORD. The cylinder does not refer to this decree, but it shows that such a policy was consistent with the way Cyrus governed. Isaiah names Cyrus as the one through whom the LORD would bring about the rebuilding of Jerusalem and the temple.",
        "refs": "2 Chronicles 36:22–23; Ezra 1:1–4; 6:3–5; Isaiah 44:28–45:1",
        "verse": ("Ezra 1:2", "Thus saith Cyrus king of Persia, The LORD God of heaven hath given me all the kingdoms of the earth; and he hath charged me to build him an house at Jerusalem, which is in Judah."),
        "handbook": "On the Handbook's biblical timeline, find the beginning of Persian rule (539 BC), when Cyrus, king of Persia, ordered the return of the Jews (538 BC), followed by the restoration period with Haggai and Zechariah.",
        "question": "God worked even through a foreign king to bring His people home. Where have you seen God at work through unexpected people or circumstances?",
    },
    {
        "name": "The Pilate Stone",
        "date": "AD 26–36",
        "art": "block",
        "found": "1961, by Italian archaeologists led by Antonio Frova, in the Roman theatre at Caesarea Maritima, Israel, where the stone had been reused in a later building phase",
        "kept": "Israel Museum, Jerusalem (a replica stands at Caesarea)",
        "object": "A limestone block with a partly preserved Latin inscription",
        "what": "A dedication stone from a building in honour of the emperor Tiberius (a “Tiberieum”) at Caesarea, the Roman administrative centre of Judea.",
        "evidence": "The inscription names <em>Pontius Pilate</em> and gives his title as prefect of Judea. It is the only known stone inscription from Pilate's own time that names him.",
        "context": "The stone shows that Pilate governed Judea under the emperor Tiberius and gives his official title. Pilate is also mentioned by the Jewish writers Philo and Josephus and by the Roman historian Tacitus.",
        "bible": "All four Gospels name Pontius Pilate as the Roman governor before whom Jesus was tried and who handed Him over to be crucified. Luke dates the beginning of John the Baptist's ministry to the fifteenth year of Tiberius, when Pilate was governor of Judea. The stone places Pilate in the same office and the same period.",
        "refs": "Matthew 27:1–26; Mark 15:1–15; Luke 3:1; 23:1–25; John 18:28–19:16",
        "verse": ("Luke 3:1", "Now in the fifteenth year of the reign of Tiberius Cæsar, Pontius Pilate being governor of Judæa, and Herod being tetrarch of Galilee, …"),
        "handbook": "On the Handbook's biblical timeline, find the life of Jesus: His baptism and the beginning of His public ministry, and His death and resurrection (AD 30), which took place while Pilate governed Judea.",
        "question": "Pilate asked, “What is truth?” (John 18:38) while standing before Jesus. How would you answer that question today?",
    },
    {
        "name": "The Gallio Inscription (Delphi Inscription)",
        "date": "c. AD 52",
        "art": "gallio",
        "found": "Fragments found at Delphi, Greece, during French excavations; first published in 1905, with further fragments identified later",
        "kept": "Delphi Archaeological Museum, Greece",
        "object": "Several fragments of a stone inscription in Greek",
        "what": "A copy of a letter from the Roman emperor Claudius to the city of Delphi, set up publicly at the sanctuary of Apollo.",
        "evidence": "The emperor refers to <em>Gallio</em> as his friend and proconsul (governor) of the province of Achaia. The letter is dated by Claudius' 26th acclamation as emperor, which places it in AD 52, most probably between January and August.",
        "context": "Roman proconsuls of this kind usually served for one year. Using this inscription, historians date Gallio's term in Achaia to about AD 51–52 (some prefer AD 50–51). Gallio was the brother of the philosopher Seneca.",
        "bible": "Acts 18 records that while Paul was in Corinth, the capital of Achaia, he was brought before Gallio's judgment seat, and Gallio refused to hear the case. Because Gallio's term can be dated, this inscription is one of the key fixed points for dating Paul's stay in Corinth and the chronology of his journeys and letters.",
        "refs": "Acts 18:1–17",
        "verse": ("Acts 18:12", "And when Gallio was the deputy of Achaia, the Jews made insurrection with one accord against Paul, and brought him to the judgment seat,"),
        "handbook": "In the Handbook, look at the visual presentation of Paul's three missionary journeys and, on the biblical timeline, the second missionary journey of Paul (c. AD 50–52), during which Paul stayed in Corinth.",
        "question": "Paul kept preaching in Corinth after the Lord told him, “Be not afraid, but speak” (Acts 18:9). Where might God be calling you to speak about your faith?",
    },
]
